platform :ios, '11.0'
use_frameworks!
inhibit_all_warnings!
install! 'cocoapods',
         :deterministic_uuids => false

def main_pods
    pod 'Socket.IO-Client-Swift'
end

post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end
    end
end

target 'socketIO' do
    main_pods
end
